language: ruby
rvm:
  - "2.1.7"
  - "2.2.3"
gemfiles:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
env:
  global:
    TRAVIS: true
